INSERT INTO Ingredients(name) VALUES('beef roast');
INSERT INTO Ingredients(name) VALUES('brown gravy mix');
INSERT INTO Ingredients(name) VALUES('dried Italian salad dressing mix');
INSERT INTO Ingredients(name) VALUES('dry ranch dressing mix');
INSERT INTO Ingredients(name) VALUES('water');
INSERT INTO Ingredients(name) VALUES('asparagus');
INSERT INTO Ingredients(name) VALUES('olive oil');
INSERT INTO Ingredients(name) VALUES('kosher salt');
INSERT INTO Ingredients(name) VALUES('beef broth');
INSERT INTO Ingredients(name) VALUES('dried green lentils');
INSERT INTO Ingredients(name) VALUES('basmati rice');
INSERT INTO Ingredients(name) VALUES('curry powder');
INSERT INTO Ingredients(name) VALUES('salt');
INSERT INTO Ingredients(name) VALUES('yeast');
INSERT INTO Ingredients(name) VALUES('flour');
INSERT INTO Ingredients(name) VALUES('vegetable oil');
INSERT INTO Ingredients(name) VALUES('sugar');
INSERT INTO Ingredients(name) VALUES('hot water');
INSERT INTO Ingredients(name) VALUES('pizza sauce');
INSERT INTO Ingredients(name) VALUES('mozzarella cheese');
INSERT INTO Ingredients(name) VALUES('acorn squash');
INSERT INTO Ingredients(name) VALUES('boiling water');
INSERT INTO Ingredients(name) VALUES('apples chopped into 1.4 inch pieces');
INSERT INTO Ingredients(name) VALUES('dried cranberries');
INSERT INTO Ingredients(name) VALUES('cinnamon');
INSERT INTO Ingredients(name) VALUES('melted butter');
INSERT INTO Ingredients(name) VALUES('plain flour');
INSERT INTO Ingredients(name) VALUES('eggs');
INSERT INTO Ingredients(name) VALUES('milk');
INSERT INTO Ingredients(name) VALUES('raisins');
INSERT INTO Ingredients(name) VALUES('cup water');
INSERT INTO Ingredients(name) VALUES('shortening');
INSERT INTO Ingredients(name) VALUES('soda');
INSERT INTO Ingredients(name) VALUES('baking powder');
INSERT INTO Ingredients(name) VALUES('cloves');
INSERT INTO Ingredients(name) VALUES('oats');
INSERT INTO Ingredients(name) VALUES('chopped nuts');
INSERT INTO Ingredients(name) VALUES('rolled oats, (not instant)');
INSERT INTO Ingredients(name) VALUES('all-purpose flour');
INSERT INTO Ingredients(name) VALUES('grated orange rind');
INSERT INTO Ingredients(name) VALUES('cold butter, cubed');
INSERT INTO Ingredients(name) VALUES('packed brown sugar');
INSERT INTO Ingredients(name) VALUES('fresh blueberries');
INSERT INTO Ingredients(name) VALUES('granulated sugar');
INSERT INTO Ingredients(name) VALUES('orange juice');
INSERT INTO Ingredients(name) VALUES('cornstarch');
INSERT INTO Ingredients(name) VALUES('skinless, boneless chicken breasts, halved lengthwise');
INSERT INTO Ingredients(name) VALUES('mayonnaise');
INSERT INTO Ingredients(name) VALUES('lemon zest');
INSERT INTO Ingredients(name) VALUES('lemon juice');
INSERT INTO Ingredients(name) VALUES('ripe mangoes, diced');
INSERT INTO Ingredients(name) VALUES('green onions, thinly sliced');
INSERT INTO Ingredients(name) VALUES('celery stalk, finely chopped');
INSERT INTO Ingredients(name) VALUES('Boston lettuce');
INSERT INTO Ingredients(name) VALUES('English muffins, toasted');
INSERT INTO Measurements(unit) VALUES('g');
INSERT INTO Measurements(unit) VALUES('lb');
INSERT INTO Measurements(unit) VALUES('tbsp');
INSERT INTO Measurements(unit) VALUES('teaspoon');
INSERT INTO Measurements(unit) VALUES('tablespoons');
INSERT INTO Measurements(unit) VALUES('leaves');
INSERT INTO Measurements(unit) VALUES('tsp.');
INSERT INTO Measurements(unit) VALUES('teaspoons');
INSERT INTO Measurements(unit) VALUES('quart');
INSERT INTO Measurements(unit) VALUES('ml');
INSERT INTO Measurements(unit) VALUES('tsp');
INSERT INTO Measurements(unit) VALUES('cups');
INSERT INTO Measurements(unit) VALUES('cup');
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='g'), (SELECT ingredient_id FROM Ingredients WHERE name='brown gravy mix'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='g'), (SELECT ingredient_id FROM Ingredients WHERE name='dried Italian salad dressing mix'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='g'), (SELECT ingredient_id FROM Ingredients WHERE name='dry ranch dressing mix'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cup'), (SELECT ingredient_id FROM Ingredients WHERE name='water'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='lb'), (SELECT ingredient_id FROM Ingredients WHERE name='asparagus'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='tbsp'), (SELECT ingredient_id FROM Ingredients WHERE name='olive oil'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='tsp'), (SELECT ingredient_id FROM Ingredients WHERE name='kosher salt'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='quart'), (SELECT ingredient_id FROM Ingredients WHERE name='beef broth'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cup'), (SELECT ingredient_id FROM Ingredients WHERE name='dried green lentils'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cup'), (SELECT ingredient_id FROM Ingredients WHERE name='basmati rice'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='tsp'), (SELECT ingredient_id FROM Ingredients WHERE name='curry powder'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='tsp'), (SELECT ingredient_id FROM Ingredients WHERE name='salt'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='teaspoons'), (SELECT ingredient_id FROM Ingredients WHERE name='yeast'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cups'), (SELECT ingredient_id FROM Ingredients WHERE name='flour'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='tablespoons'), (SELECT ingredient_id FROM Ingredients WHERE name='vegetable oil'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='tablespoons'), (SELECT ingredient_id FROM Ingredients WHERE name='sugar'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cups'), (SELECT ingredient_id FROM Ingredients WHERE name='hot water'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cup'), (SELECT ingredient_id FROM Ingredients WHERE name='pizza sauce'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cup'), (SELECT ingredient_id FROM Ingredients WHERE name='mozzarella cheese'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cup'), (SELECT ingredient_id FROM Ingredients WHERE name='dried cranberries'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='teaspoon'), (SELECT ingredient_id FROM Ingredients WHERE name='cinnamon'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='tablespoons'), (SELECT ingredient_id FROM Ingredients WHERE name='melted butter'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='g'), (SELECT ingredient_id FROM Ingredients WHERE name='plain flour'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='ml'), (SELECT ingredient_id FROM Ingredients WHERE name='milk'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cup'), (SELECT ingredient_id FROM Ingredients WHERE name='raisins'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cup'), (SELECT ingredient_id FROM Ingredients WHERE name='shortening'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='tsp.'), (SELECT ingredient_id FROM Ingredients WHERE name='soda'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='tsp.'), (SELECT ingredient_id FROM Ingredients WHERE name='baking powder'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='tsp.'), (SELECT ingredient_id FROM Ingredients WHERE name='cloves'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cups'), (SELECT ingredient_id FROM Ingredients WHERE name='oats'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cup'), (SELECT ingredient_id FROM Ingredients WHERE name='chopped nuts'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cups'), (SELECT ingredient_id FROM Ingredients WHERE name='rolled oats, (not instant)'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cups'), (SELECT ingredient_id FROM Ingredients WHERE name='all-purpose flour'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='tbsp'), (SELECT ingredient_id FROM Ingredients WHERE name='grated orange rind'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cup'), (SELECT ingredient_id FROM Ingredients WHERE name='cold butter, cubed'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cup'), (SELECT ingredient_id FROM Ingredients WHERE name='packed brown sugar'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cups'), (SELECT ingredient_id FROM Ingredients WHERE name='fresh blueberries'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cup'), (SELECT ingredient_id FROM Ingredients WHERE name='granulated sugar'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cup'), (SELECT ingredient_id FROM Ingredients WHERE name='orange juice'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='tsp'), (SELECT ingredient_id FROM Ingredients WHERE name='cornstarch'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='cup'), (SELECT ingredient_id FROM Ingredients WHERE name='mayonnaise'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='tbsp'), (SELECT ingredient_id FROM Ingredients WHERE name='lemon zest'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit=''), (SELECT ingredient_id FROM Ingredients WHERE name='lemon juice'));
INSERT INTO Measurements_Ingredients(measure_id, ingredient_id) VALUES((SELECT measure_id FROM Measurements WHERE unit='leaves'), (SELECT ingredient_id FROM Ingredients WHERE name='Boston lettuce'));
