INSERT INTO USERS(first_name,last_name,email,password) VALUES('Megan','Lewis','MeganLewis@gmail.com','<sha256 _hashlib.HASH object @ 0x000001FCA699A3B0>');
INSERT INTO RECIPES(name,date_created,user_id) VALUES('Crock Pot Roast','2021-04-02 23:19:16.194472',(SELECT Users.user_id from Users ORDER BY Users.user_id DESC LIMIT 1));
INSERT INTO INSTRUCTIONS(recipe_id,step) VALUES((SELECT recipe_id from RECIPES ORDER BY recipes.recipe_id DESC LIMIT 1),'Cook on low for 7-9 hours.');
INSERT INTO RECIPES(name,date_created,user_id) VALUES('Mic Yorkshire Puds','2021-04-02 23:19:16.194472',(SELECT Users.user_id from Users ORDER BY Users.user_id DESC LIMIT 1));
INSERT INTO INSTRUCTIONS(recipe_id,step) VALUES((SELECT recipe_id from RECIPES ORDER BY recipes.recipe_id DESC LIMIT 1),'Bake for 30 minutes until well browned and risen.');
INSERT INTO RECIPES(name,date_created,user_id) VALUES('Old-Fashioned Oatmeal Cookies','2021-04-02 23:19:16.194472',(SELECT Users.user_id from Users ORDER BY Users.user_id DESC LIMIT 1));
INSERT INTO INSTRUCTIONS(recipe_id,step) VALUES((SELECT recipe_id from RECIPES ORDER BY recipes.recipe_id DESC LIMIT 1),'About 6 1/2 dozen cookies.');
INSERT INTO USERS(first_name,last_name,email,password) VALUES('Valerie','Bright','ValerieBright@outlook.com','<sha256 _hashlib.HASH object @ 0x000001FCA699A3B0>');
INSERT INTO RECIPES(name,date_created,user_id) VALUES('Crock Pot Roast','2021-04-02 23:19:16.194472',(SELECT Users.user_id from Users ORDER BY Users.user_id DESC LIMIT 1));
INSERT INTO INSTRUCTIONS(recipe_id,step) VALUES((SELECT recipe_id from RECIPES ORDER BY recipes.recipe_id DESC LIMIT 1),'Cook on low for 7-9 hours.');
INSERT INTO RECIPES(name,date_created,user_id) VALUES('Roasted Asparagus','2021-04-02 23:19:16.194472',(SELECT Users.user_id from Users ORDER BY Users.user_id DESC LIMIT 1));
INSERT INTO INSTRUCTIONS(recipe_id,step) VALUES((SELECT recipe_id from RECIPES ORDER BY recipes.recipe_id DESC LIMIT 1),'They are great plain, but sometimes I serve them with a light vinaigrette if we need something acidic to balance out our meal.');
INSERT INTO RECIPES(name,date_created,user_id) VALUES('Mic Yorkshire Puds','2021-04-02 23:19:16.194472',(SELECT Users.user_id from Users ORDER BY Users.user_id DESC LIMIT 1));
INSERT INTO INSTRUCTIONS(recipe_id,step) VALUES((SELECT recipe_id from RECIPES ORDER BY recipes.recipe_id DESC LIMIT 1),'Bake for 30 minutes until well browned and risen.');
INSERT INTO USERS(first_name,last_name,email,password) VALUES('Jeremy','Gonzalez','JeremyGonzalez@outlook.com','<sha256 _hashlib.HASH object @ 0x000001FCA699A3B0>');
INSERT INTO RECIPES(name,date_created,user_id) VALUES('Roasted Asparagus','2021-04-02 23:19:16.195467',(SELECT Users.user_id from Users ORDER BY Users.user_id DESC LIMIT 1));
INSERT INTO INSTRUCTIONS(recipe_id,step) VALUES((SELECT recipe_id from RECIPES ORDER BY recipes.recipe_id DESC LIMIT 1),'They are great plain, but sometimes I serve them with a light vinaigrette if we need something acidic to balance out our meal.');
INSERT INTO RECIPES(name,date_created,user_id) VALUES('Curried chicken salad','2021-04-02 23:19:16.195467',(SELECT Users.user_id from Users ORDER BY Users.user_id DESC LIMIT 1));
INSERT INTO INSTRUCTIONS(recipe_id,step) VALUES((SELECT recipe_id from RECIPES ORDER BY recipes.recipe_id DESC LIMIT 1),'Sandwich with tops');
INSERT INTO RECIPES(name,date_created,user_id) VALUES('Old-Fashioned Oatmeal Cookies','2021-04-02 23:19:16.195467',(SELECT Users.user_id from Users ORDER BY Users.user_id DESC LIMIT 1));
INSERT INTO INSTRUCTIONS(recipe_id,step) VALUES((SELECT recipe_id from RECIPES ORDER BY recipes.recipe_id DESC LIMIT 1),'About 6 1/2 dozen cookies.');
